version: '3.4'
services:
  react-fe:
    image: ravenholm/react-fe
    build: ./react-fe
    command: [echo, "Run react frontend locally for development!"]
  rpi-api:
    image: ravenholm/rpi-api
    build: ./rpi-api
    environment:
    - FLASK_ENV=development
    - POSTGRES_HOST
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    ports:
    - 5000:5000
    volumes:
    - ./rpi-api:/usr/src/app
    depends_on:
    - db
  db:
    image: postgres:alpine
    ports:
    - 5431:5432
    environment:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    volumes:
    - ./db:/docker-entrypoint-initdb.d
