on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Build :latests
      run: docker-compose build
      
    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push react-fe
      uses: actions-hub/docker@master
      with:
        args: push ${{ secrets.DOCKER_REGISTRY }}/ravenholm/react-fe:latest
