on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build :latests
      run: docker-compose build

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_REGISTRY_URL: junction2019.azurecr.io
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push react-fe
      uses: actions-hub/docker@master
      with:
        args: push junction2019.azurecr.io/ravenholm/react-fe:latest

    - name: Push backend
      uses: actions-hub/docker@master
      with:
        args: push junction2019.azurecr.io/ravenholm/backend:latest
